import Header from "@/components/Header";
import "./globals.css";
import { Inter, Mulish } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const mulish = Mulish({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Here children is our page.js
function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
